[platformio]
default_envs = tx, rx

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

[env:tx]
build_src_filter = +<transmitter.cpp>
lib_deps = arduino-libraries/LiquidCrystal
upload_port  = /dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_75135303739351212212-if00
monitor_port = /dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_75135303739351212212-if00

[env:rx]
build_src_filter = +<reciever.cpp>
lib_deps = marcoschwartz/LiquidCrystal_I2C
upload_port  = /dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_55139313535351E01031-if00
monitor_port = /dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_55139313535351E01031-if00
build_flags = -D SAITE_IQ