[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    arduino-libraries/LiquidCrystal
build_type = debug

build_unflags = -Os
build_flags = -O0 -g3 -ggdb3

build_src_flags =
    -Wall -Wextra -Wshadow -Wconversion -Wsign-conversion

check_tool = cppcheck, clangtidy
check_flags =
    cppcheck: --enable=all --addon=misra --suppress=missingInclude
    clangtidy: --checks=-*,bugprone-*,cert-*,readability-*
check_skip_packages = yes